### ISSUE TITLE
Can't get results for LunarLander

### ISSUE THREAD

**Issue by TrentBrick** [BY571/Upside-Down-Reinforcement-Learning#4]
Hi thanks for sharing your code and implementation. 

However, when running your notebook with the LunarLander-v2, even with 1,000 epochs it doesn't seem to be learning anything: 

![image](https://user-images.githubusercontent.com/12433427/87363950-3e42ec80-c56a-11ea-871e-8154327cdc3d.png)

Can you share the hyperparameters necessary to reproduce the LunarLander? 

Thank you.

**Comment by BY571** [comment]
hello @TrentBrick !
Sure, here the hyperparameter:
    "horizon_scale" : 0.01,
    "return_scale" : 0.025,
    "replay_size" : 500,
    "n_warm_up_episodes" : 10,
    "n_updates_per_iter" : 100,
    "n_episodes_per_iter" : 20,
    "last_few" : 75,
    "batch_size" : 768,
    "layer_size" : 128,
    "learning_rate" : 1e-3

**Comment by TrentBrick** [comment]
Thanks for getting back to me and sharing these parameters. I just tried them but they also dont seem to be working for me. 

![image](https://user-images.githubusercontent.com/12433427/87734043-61b7a280-c7c9-11ea-8b93-3e958b639970.png)

**Comment by BY571** [comment]
oh, I just noticed that there is an older network architecture. try to add two linear layers, it should work then.
Thanks for noticing, ill update the code!

**Comment by TrentBrick** [comment]
Just heads up I've moved on to using other repos for this. Spent too long trying to run yours. You should double check that everything now works though for future people that come across this repo.

**Comment by tangzk** [comment]
> oh, I just noticed that there is an older network architecture. try to add two linear layers, it should work then. Thanks for noticing, ill update the code!

@BY571  Have you updated the latest code? I got results similar to TrentBrick in LunarLander-v2 env.

**Comment by TrentBrick** [comment]
@tangzk if you want to use my repo for this... https://github.com/TrentBrick/RewardConditionedUDRL
